import Registry from 'uidata/model/Registry'

import './ActorRelations'
import './Annotation'
import './AnnotationCategory'
import './Category'
import './Chapter'
import './Contact'
import './ContactPerson'
import './Event'
import './Facet'
import './FacetItem'
import './Location'
import './MetaData'
import './Navigation'
import './NavigationItem'
import './Offer'
import './Orga'
import './ResourceItem'
import './User'

Registry.initializeAll()
